name: Build Container

on:
  push:
    branches:
      - main
    paths:
      - "**"
  schedule:
    - cron: '17 5 * * 2'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          tags: latest
          tag_with_sha: true
          repository: ${{ github.repository }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io